name: live_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.6+5

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:

  bouncing_draggable_dialog: ^1.0.2
  clipboard: ^0.1.3
  contained_tab_bar_view: ^0.8.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_animated_dialog: ^2.0.1
  flutter_otp_text_field: ^1.1.1
  flutter_screenutil: ^5.8.4
  get: ^4.6.5
  http:
  google_fonts:
  google_nav_bar: ^5.0.6
  shared_preferences: ^2.2.0
  provider: ^6.0.5
  image_picker: ^1.0.2
  fluttertoast: ^8.2.2
  intl: ^0.18.1
  shimmer: ^3.0.0
  like_button: ^2.0.5
  photo_view: ^0.14.0
  dio: ^5.3.2
  image_cropper:
  zego_express_engine: ^3.8.1
  permission_handler: 8.1.2
  marquee_text: ^2.5.0+1
  flutter_svg: ^2.0.8
  wakelock_plus: ^1.1.4
  vertical_tabs_flutter: ^1.0.0
  pull_to_refresh: ^2.0.0
  collection: ^1.17.1
  url_launcher: ^6.1.14
  luckywheel: ^1.0.0
  flutter_fortune_wheel: ^1.3.0
  flutter_image_slideshow: ^0.1.6
  intl_phone_number_input: ^0.7.3+1
  country_flags: ^2.2.0
  webview_flutter: ^3.0.0
  on_audio_query: ^2.9.0
  internet_connection_checker_plus: ^1.0.1
#  firebase_core: ^2.21.0
#  firebase_auth: ^4.12.1
#  google_sign_in: ^6.1.5

dependency_overrides:
  svgaplayer_flutter:

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/dummy/
    - assets/treas/
    - assets/gifts/
    - assets/emoji/
    - assets/agency/
    - assets/icon_p/
    - assets/room_icons/
    - assets/decoration/
    - assets/level_badge/
    - assets/svip_benefits_ic/
    - assets/ic_treasure_box/
