name: live_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.13+13

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.8.4
  flutter_animated_dialog: ^2.0.1
  contained_tab_bar_view: ^0.8.0
  flutter_otp_text_field: ^1.1.1
  bouncing_draggable_dialog: ^1.0.2
  dio: ^5.3.2
  get: ^4.6.5
  intl: ^0.19.0
  http: ^0.13.6
  shimmer: ^3.0.0
  provider: ^6.0.5
  clipboard: ^0.1.3
  like_button: ^2.0.5
  http_parser: ^4.0.2
  google_fonts: ^4.0.4
  image_cropper: ^4.0.1
  svgaplayer_flutter: ^2.2.0
  google_nav_bar: ^5.0.6
  shared_preferences: ^2.2.0
  image_picker: ^1.0.2
  fluttertoast: ^8.2.2
  zego_express_engine: ^3.8.1
  vertical_tabs_flutter: ^1.0.0
  permission_handler: ^11.3.0
  marquee_text: ^2.5.0+1
  flutter_svg: ^2.0.8
  wakelock_plus: ^1.1.4
  pull_to_refresh: ^2.0.0
  collection: ^1.17.1
  url_launcher: ^6.1.14
  luckywheel: ^1.0.0
  flutter_fortune_wheel: ^1.3.0
  flutter_image_slideshow: ^0.1.6
  intl_phone_number_input: ^0.7.3+1
  country_flags: ^2.2.0
  webview_flutter: ^4.7.0
  on_audio_query: ^2.9.0
  in_app_purchase: ^3.1.13
  firebase_core: ^2.24.2
  cloud_firestore: ^4.14.0
  phonepe_payment_sdk: ^2.0.1
#  firebase_auth: ^4.12.1
#  google_sign_in: ^6.1.5

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/dummy/
    - assets/treas/
    - assets/gifts/
    - assets/emoji/
    - assets/games/
    - assets/agency/
    - assets/icon_p/
    - assets/entry_bg/
    - assets/room_icons/
    - assets/decoration/
    - assets/level_badge/
    - assets/svip_benefits_ic/
    - assets/ic_treasure_box/
